#!/usr/bin/env bash
cat << "EOF"
__        __   _                            _
\ \      / /__| | ___ ___  _ __ ___   ___  | |_ ___
 \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ | __/ _ \
  \ V  V /  __/ | (_| (_) | | | | | |  __/ | || (_) |
   \_/\_/ \___|_|\___\___/|_| |_| |_|\___|  \__\___/

 ____        _____ ___  ____   ____
|  _ \ _   _|  ___/ _ \/ ___| / ___|
| |_) | | | | |_ | | | \___ \| |
|  __/| |_| |  _|| |_| |___) | |___
|_|    \__, |_|   \___/|____/ \____|
       |___/
EOF
CWD=$(pwd -P)
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
function render_template() {
  eval "echo \"$(cat $1)\""
}
printf "Make sure you have already prepared the data and initiated\niraf before doing the following.\n"
printf "The current working directory is $CWD.\n"
printf "The source directory is $BASEDIR.\n"
if [ ! -d "./raw" ]; then
  mkdir ./raw
  printf "Directory \"raw\" is created.\n"
else
  printf "Directory \"raw\" already exists.\n"
fi
if [ ! -d "./data" ]; then
  mkdir ./data
  printf "Directory \"data\" is created.\n"
else
  printf "Directory \"data\" already exists.\n"
fi
if [ ! -d "./data/database" ]; then
  mkdir ./data/database
  printf "Directory \"data/database\" is created.\n"
else
  printf "Directory \"data/database\" already exists.\n"
fi
printf "============================================================\n"
title="Please select the instrument with which you took the spectra."
prompt="Enter number after the prompt:"
options=("BFOSC, Xinglong 2m16 telescope" "YFOSC, Lijiang 2m4 telescope" "HFOSC, HCT at IAO" "DBSP, P200 at Palomar Observatory")

echo "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do

    case "$REPLY" in

    1 ) printf "============================================================\n"
    TELESCOPE="XLT"
    echo "You picked $opt which is option $REPLY."
    while true; do
    # read -p "Enter the slit you have used (e.g. slit2.5):" slit
    read -p "Enter the Grism you have used (e.g. G4):" Grism
    render_template $BASEDIR/config/instrconfig.json.temp > ./myfosc.json
    cp ./myfosc.json ./data/
    read -p "Do you want to copy the raw files to ./raw?[y/n]" yn
        case $yn in
          [Yy]* ) python $BASEDIR/src/list_backup_data.py; echo "Raw data is backuped and copied to ./raw."; exit;;
          [Nn]* ) echo "Otherwise you have to do it yourself."; exit;;
          * ) echo "Please answer y or n.";;
        esac
    done
    break;;
    2 ) printf "============================================================\n"
    TELESCOPE="LJT"
    echo "You picked $opt which is option $REPLY."
    while true; do
    read -p "Enter the slit you have used (e.g. slit2.5):" slit
    read -p "Enter the Grism you have used (e.g. G3):" Grism
    render_template $BASEDIR/config/instrconfig.json.temp > ./myfosc.json
    cp ./myfosc.json ./data/
    read -p "Do you want to copy the raw files to ./raw?[y/n]" yn
        case $yn in
          [Yy]* ) python $BASEDIR/src/list_backup_data.py; echo "Raw data is backuped and copied to ./raw."; exit;;
          [Nn]* ) echo "Otherwise you have to do it yourself."; exit;;
          * ) echo "Please answer y or n.";;
        esac
    done
    break;;
    3 ) printf "============================================================\n"
    TELESCOPE="HCT"
    echo "You picked $opt which is option $REPLY."
    while true; do
    read -p "Enter the slit you have used (e.g. s167; s134):" slit
    read -p "Enter the Grism you have used (e.g. Gr7):" Grism
    render_template $BASEDIR/config/instrconfig.json.temp > ./myfosc.json
    cp ./myfosc.json ./data/
    read -p "Do you want to copy the raw files to ./raw?[y/n]" yn
        case $yn in
          [Yy]* ) python $BASEDIR/src/list_backup_data.py; echo "Raw data is backuped and copied to ./raw."; exit;;
          [Nn]* ) echo "Otherwise you have to do it yourself."; exit;;
          * ) echo "Please answer y or n.";;
        esac
    done
    break;;
    4 ) printf "============================================================\n"
    TELESCOPE="P200"
    echo "You picked $opt which is option $REPLY."
    while true; do
    read -p "Please choose the channel (blue [b] or red [r]) of the data you want to reduce. [b/r]:" br
        case $br in
          [Bb]* ) side="blue" ; echo "You picked blue channel.";;
          [Rr]* ) side="red" ; echo "You picked red channel.";;
          * ) echo "Please answer b or r.";;
        esac
    render_template $BASEDIR/config/instrconfig.json.temp > ./myfosc.json
    cp ./myfosc.json ./data/
    read -p "Do you want to copy the raw files to ./raw?[y/n]" yn
        case $yn in
          [Yy]* ) python $BASEDIR/src/list_backup_data.py; echo "Raw data is backuped and copied to ./raw."; exit;;
          [Nn]* ) echo "Otherwise you have to do it yourself."; exit;;
          * ) echo "Please answer y or n.";;
        esac
    done
    break;;
    5 ) printf "============================================================\n"
    echo "You picked $opt which is option $REPLY.";;

    $(( ${#options[@]}+1 )) ) echo "Goodbye!"; break;;
    *) echo "Invalid option. Try another one.";continue;;

    esac

done
