#!/usr/bin/env bash
cat << "EOF"
__        __   _                            _
\ \      / /__| | ___ ___  _ __ ___   ___  | |_ ___
 \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ | __/ _ \
  \ V  V /  __/ | (_| (_) | | | | | |  __/ | || (_) |
   \_/\_/ \___|_|\___\___/|_| |_| |_|\___|  \__\___/

 ____        _____ ___  ____   ____
|  _ \ _   _|  ___/ _ \/ ___| / ___|
| |_) | | | | |_ | | | \___ \| |
|  __/| |_| |  _|| |_| |___) | |___
|_|    \__, |_|   \___/|____/ \____|
       |___/
EOF
CWD=$(pwd -P)
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
function render_template() {
  eval "echo \"$(cat $1)\""
}
printf "Make sure you have already prepared the data and initiated\niraf before doing the following.\n"
printf "The current working directory is $CWD.\n"
printf "The source directory is $BASEDIR.\n"
if [ ! -d "./raw" ]; then
  mkdir ./raw
  printf "Directory \"raw\" is created.\n"
else
  printf "Directory \"raw\" already exists.\n"
fi
printf "============================================================\n"
title="Please select the instrument with which you took the spectra."
prompt="Enter number after the prompt:"
options=("BFOSC, Xinglong 2m16 telescope" "YFOSC, Lijiang 2m4 telescope")

echo "$title"
PS3="$prompt "
select opt in "${options[@]}" "Quit"; do

    case "$REPLY" in

    1 ) printf "============================================================\n"
    TELESCOPE="XLT"
    cp $BASEDIR/iraf_scripts/genlistXLT.cl $CWD
    cp $BASEDIR/iraf_scripts/genlistXLT2021.cl $CWD
    echo "You picked $opt which is option $REPLY."
    while true; do
    # read -p "Enter the slit you have used (e.g. slit2.5):" slit
    read -p "Enter the Grism you have used (e.g. G4):" Grism
    render_template $BASEDIR/config/instrconfig.json.temp > ./myfosc.json
    read -p "Do you want to copy the raw files to ./raw?[y/n]" yn
        case $yn in
          [Yy]* ) bash $BASEDIR/src/cpxlraw.sh; echo "Raw data is backuped and copied to ./raw."; exit;;
          [Nn]* ) echo "Otherwise you have to do it yourself."; exit;;
          * ) echo "Please answer y or n.";;
        esac
    done
    break;;
    2 ) printf "============================================================\n"
    TELESCOPE="LJT"
    cp $BASEDIR/iraf_scripts/genlistLJT.cl $CWD
    echo "You picked $opt which is option $REPLY."
    while true; do
    read -p "Enter the slit you have used (e.g. slit2.5):" slit
    read -p "Enter the Grism you have used (e.g. G3):" Grism
    render_template $BASEDIR/config/instrconfig.json.temp > ./myfosc.json
    read -p "Do you want to copy the raw files to ./raw?[y/n]" yn
        case $yn in
          [Yy]* ) bash $BASEDIR/src/cpfstext.sh; echo "Raw data is backuped and copied to ./raw."; exit;;
          [Nn]* ) echo "Otherwise you have to do it yourself."; exit;;
          * ) echo "Please answer y or n.";;
        esac
    done
    break;;
    3 ) printf "============================================================\n"
    echo "You picked $opt which is option $REPLY.";;

    $(( ${#options[@]}+1 )) ) echo "Goodbye!"; break;;
    *) echo "Invalid option. Try another one.";continue;;

    esac

done
